notifications:
  email: false

# Enable C++ support
language: cpp

# Compiler selection
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gdb
      - gcc-6
      - g++-6
      - cmake
      - build-essential
      - libreadline6
      - libreadline6-dev
      - libboost-all-dev

before_install:
  - export CXX="g++-6" CC="gcc-6"

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
