# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

boost:
  - 1.59.0
  - 1.60.0

before_install:
  - sudo apt-get install -y libreadline6 libreadline6-dev

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
